### ISSUE TITLE
pcre version upgrade

### ISSUE THREAD

**Issue by santos101** [iuscommunity-pkg/php70u#10]
Hi,

Was wondering if you were planning on upgrading the version of PCRE in the repo?

I've just installed php70u, which is still running;

PCRE Library Version => 8.32 2012-11-30 

seems this version has been replaced since then, and other repos have a newer version running;

PCRE Library Version => 8.38 2015-11-23

Many thanks,

Chris

**Comment by carlwgeorge** [comment]
Howdy @santos101,

What you observing is that we [build against the system copy of PCRE on EL7](https://github.com/iuscommunity-pkg/php70u/commit/d89f5c823cdb5b1aff0943848790e66afb5f0091).  [We](https://bugs.launchpad.net/ius/+bug/608119) [have](https://bugs.launchpad.net/ius/+bug/1039187) [gone](https://bugs.launchpad.net/ius/+bug/1215089) [back](https://github.com/iuscommunity-pkg/php56u/pull/1) [and](https://github.com/iuscommunity-pkg/php56u/commit/1834368addfcfdf72daeafcc105d648c1d2dd069) [forth](https://lists.launchpad.net/ius-community/msg01714.html) over the years between using the bundled PCRE and using the system library.  Just like Fedora and RHEL, we have a strong preference to use system libraries over bundled libraries whenever possible.  That said, we understand that it may be unavoidable at times.  PHP 7.0 [started with PCRE 8.37 bundled, and has since bumped to version 8.38](http://php.net/manual/en/pcre.installation.php).  It should be pretty straightforward to set `%with_libpcre` to 0 on all releases to switch back to the bundled copy.  In fact, we just created php71u and are going to [stick with the bundled PCRE on all RHEL releases](https://github.com/iuscommunity-pkg/php71u/commit/c219148a105ef8c4c8e147be4cee3e768496d9d6), at least initially.

All that said, IUS has never been about using the latest version for the sake of using the latest version.  Are there any specific improvements/features/bug fixes in PCRE 8.38 that you are missing out on?

**Comment by Xon** [comment]
IUS's CentOS6 PHP 7.0.13 packages already provide PCRE 8.38 2015-11-23

The actual latest 8.xx version of PCRE is [8.39 14-June-2016](http://www.pcre.org/original/changelog.txt)

**Comment by santos101** [comment]
HI @Xon Its quite possibly my lack of knowledge, but I installed 7.0.13 yesterday from the repo and found the older version;

php --ri pcre | grep -i version
PCRE Library Version => 8.32 2012-11-30
[root@ip-172-31-7-187 ~]# php -v
PHP 7.0.13 (cli) (built: Nov 10 2016 08:44:04) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies

@carlwgeorge Thanks, it looks like we can use php71u, any idea when it'll be promoted from testing?

**Comment by carlwgeorge** [comment]
@Xon The system PCRE library is much older on EL6 (7.8), so we already use the bundled library (8.38) there.  If @santos101 is seeing PCRE 8.32, that means he is using the EL7 packages which are built against the system PCRE (8.32).  Check out [this commit](https://github.com/iuscommunity-pkg/php70u/commit/d89f5c823cdb5b1aff0943848790e66afb5f0091).

@santos101 The php71u packages are waiting for user feedback before we promote them to stable.  You can test and provide that feedback [here](https://github.com/iuscommunity/wishlist/issues/102) to help the process move forward.  We just got the request last Friday, so we haven't built anything other than the main package and subpackage (no pecl modules yet).

**Comment by santos101** [comment]
@carlwgeorge Thanks, I'll speak to my dev guys and see if we can build against them.

**Comment by carlwgeorge** [comment]
I went ahead and made the change (026ee92) to build against the bundled PCRE on both RHEL 6 and 7, so that the php70u and php71u stacks are in line.  You can see that in the [7.0.14-2 release](https://github.com/iuscommunity-pkg/php70u/releases/7.0.14-2).  Check it out and let us know if that works for you as expected.

**Comment by b-harper** [comment]
The php70u-7.0.14-2 packages with bundled PCRE are now available in the stable repositories.
