### ISSUE TITLE
php7u - zend_mm_heap corrupted

### ISSUE THREAD

**Issue by futureweb** [iuscommunity-pkg/php70u#6]
Hi there,
since I updated to IUS PHP 7 I sometimes see: "zend_mm_heap corrupted" Error within Apache Error logs. It's not always happening on the same Page - it's completely random when & where it happens.
Page won't load when this Error is happening - but a "service httpd reload" is enough to get rid of the Problem - Page then loads normal again.
Any idea what could be the Problem here? (unfortunately not reliable reproduceable!!)
Thx
Andreas Schnederle-Wagner

**Comment by b-harper** [comment]
Hey @futureweb,

Thanks for taking the time to submit this bug.  Our first step is to determine if this an issue with the upstream project, with the way in which it get packaged or an issues with your configuration or code.  Unfortunately, there is not enough information to make that determination.  

Can you confirm which php7ou packages you are using and their versions.  Are you using mod_php?  Any configuration details that might be related?

-Ben

**Comment by futureweb** [comment]
Hey @b-harper,

using mod_php - here are the installed Packages:

> php70u-pecl-imagick-3.4.1-1.ius.centos7.x86_64
> php70u-cli-7.0.7-2.ius.centos7.x86_64
> php70u-xml-7.0.7-2.ius.centos7.x86_64
> php70u-imap-7.0.7-2.ius.centos7.x86_64
> php70u-mcrypt-7.0.7-2.ius.centos7.x86_64
> php70u-pear-1.10.1-2.ius.centos7.noarch
> php70u-pdo-7.0.7-2.ius.centos7.x86_64
> php70u-devel-7.0.7-2.ius.centos7.x86_64
> php70u-gmp-7.0.7-2.ius.centos7.x86_64
> mod_php70u-7.0.7-2.ius.centos7.x86_64
> php70u-json-7.0.7-2.ius.centos7.x86_64
> php70u-mbstring-7.0.7-2.ius.centos7.x86_64
> php70u-opcache-7.0.7-2.ius.centos7.x86_64
> php70u-common-7.0.7-2.ius.centos7.x86_64
> php70u-mysqlnd-7.0.7-2.ius.centos7.x86_64
> php70u-gd-7.0.7-2.ius.centos7.x86_64
> php70u-process-7.0.7-2.ius.centos7.x86_64

Sorry for not being able to be more specific - but didn't find a reliable way to reproduce it yet ... it's just happening randomly ...:-/

Andreas

**Comment by b-harper** [comment]
Hey @futureweb,

Thanks for that information.  Seeing that you currently do not know how to reproduce the issue, it is tough for us to investigate.  I peeked at the PHP bugs and didn't see anything that seemed fit.  You might want to look yourself.

**Comment by futureweb** [comment]
Hey @b-harper,
right now it's happening again - when calling the URL I get an OOM Error on the Page:

Fatal error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 3252197354279555072 bytes) in /docroot/php/news.php on line 197

and Errors in the Logs:
[Wed Jun 22 17:17:15.420461 2016] [core:notice] [pid 5160] AH00052: child pid 15764 exit signal Segmentation fault (11)
zend_mm_heap corrupted
[Wed Jun 22 17:19:01.859436 2016] [:error] [pid 15815] [client 212.186.24.80:51573] PHP Fatal error:  Allowed memory size of 1073741824 bytes exhausted (tried to allocate 4323808569133711360 bytes) in /docroot/php/news.php on line 197

Seems like a Memory Leak somewhere?
I think Root Cause of the Problem is OPCACHE ... as when I flush the OPCache - the Site is working again (also when doing httpd reload ... which flushes cache too)

**Comment by b-harper** [comment]
@futureweb,

Yea that looks to be a memory leak of some sort.  While I am not a PHP developer, I am not sure that OPCache is the root cause, but just another symptom.  You could attempt to role out OPCaching by disabling it and see if new.php (or others) attempt to allocate a truck load of memory.   Granted that might be tricky to do, as the problem is random and might be hard to trigger in a test environment.

**Comment by lieut-data** [comment]
Do you use Postgres with the PDO extension? I recently filed a potentially related issue against PHP7 that was later patched in PHP 7.0.8: https://bugs.php.net/bug.php?id=72294. The behaviour was erratic, including segmentation faults and heap corruption.

I haven't upgraded to PHP 7.0.8 yet to verify the patch, but it looks promising.

**Comment by futureweb** [comment]
@lieut-data, 
unfortunately we don't usw Postgres but MySQL as DB! :-/
Trying to find something reproduceable ... but no luck so far ...

**Comment by b-harper** [comment]
The PHP Group just released [7.0.8](http://php.net/archive/2016.php#id2016-06-23-1).  Looking over [the change log](http://www.php.net/ChangeLog-7.php#7.0.8), nothing jumps out to me regarding this issue.  We will have 7.0.8 packages hitting the testing repositories after tonight's automation run.  You might want to see if this issue got corrected in 7.0.8.

**Comment by futureweb** [comment]
thx - will test it when released! :)
(Even if I fear it won't help)

**Comment by futureweb** [comment]
as feared - still getting those Errors with 7.0.8 :-/

**Comment by b-harper** [comment]
@futureweb,

Thanks for the update.  Have you done any other troubleshooting or have any additional information?

**Comment by futureweb** [comment]
unfortunately I'm still not able to reproduce it ... sometimes it's running stable for days ... then again it's crashing 5x a day ... completely random! :-/

**Comment by carlwgeorge** [comment]
Just curious, can you reproduce the bug under php-fpm as well?

**Comment by futureweb** [comment]
As the Server is productive - unfortunately I can't test such things ... :-(
But I would think it should behave the same - as I think the Problem is OPCache ... a simple "opcache_reset();" and all is fine again ... no need to restart/reload Apache.

**Comment by carlwgeorge** [comment]
To troubleshoot we must isolate the issue.  This helps us establish if the problem is a packaging error (our domain) or a bug in the upstream code (which should be submitted upstream).  You unfortunately haven't given us much to go on, so this conversation hasn't been productive.  If you can't make changes to your environment to help isolate the issue, then I suggest you stand up a testing/development/staging environment where you can.  If you decide to follow my advice, here are some suggestions to try.
- Attempt to reproduce the issue using php-fpm.  The issue could be specific to the mod_php code, which would be an extremely useful detail to report upstream.
- Attempt to reproduce the issue with another third party's PHP packages, such as [Remi's repo](http://blog.remirepo.net).
- Attempt to reproduce the issue on CentOS 6.
- Attempt to reproduce the issue with another operating system that has PHP 7.0, such as Fedora 25, Ubuntu 16.04, or Arch Linux.

If the results of your troubleshooting indicate that the issue is isolated only to IUS packages, then we can re-open this issue.
