### ISSUE TITLE
php70u-fpm - problem with logrotate and ownership on /var/log/php-fpm

### ISSUE THREAD

**Issue by tgagor** [iuscommunity-pkg/php70u#8]
Hi,
I have exactly same issue with `php70u-fpm-7.0.8-1.ius.centos7.x86_64`, file: `rpm -qf /etc/logrotate.d/php-fpm`

Running logrotate on clear system:

```
# logrotate /etc/logrotate.conf 
error: skipping "/var/log/php-fpm/error.log" because parent directory has insecure permissions (It's world writable or writable by group which is not "root") Set "su" directive in config file to tell logrotate which user/group should be used for rotation.
```

I found this one with same story: https://bugzilla.redhat.com/show_bug.cgi?id=773077
Maybe solution will help you to target is sooner.

**Comment by carlwgeorge** [comment]
Howdy @tgagor,

It looks like Fedora worked around the issue by setting the group ownership of the log directory to root.  Originally this spec file was forked from Fedora, and we inherited that setting.  However, we received a [request to change it to the php-fpm group](https://github.com/iuscommunity-pkg/php70u/pull/5) in order to grant access to that directory to other users by adding them to the php-fpm group (rather than to the root group, which is obviously bad).

That bug you brought up does mention an `su` parameter for the logrotate configuration that might help.  However, on a test CentOS 7 server, I see that chrony, mariadb (mysql), nginx, rabbitmq, and redis all use non-root ownership on their log directories, without using the `su` parameter in their logrotate configuration.  I'm going to do a bit more research to determine why those setups don't raise the same error.

**Comment by tgagor** [comment]
Error message is clear - directory is group writable but should be only group readable. No one except root or process owner should be able to modify logs. 

Thanks for fast response.

**Comment by tgagor** [comment]
I checked this "[request](https://github.com/iuscommunity-pkg/php70u/pull/5)" and I'm wondering if 750 ownership will be enough to comply with both php-fpm (different pools - different users) and logrotate requirements. 
This have to be tested extensively.

**Comment by carlwgeorge** [comment]
The `su` logrotate parameter won't work because the parent php-fpm daemon runs as root and logs to `/var/log/php-fpm/error.log`, which is owned by `root:root`.  If logrotate su's to the php-fpm user, it can't rotate that file.  750 ownership fixes logrotate, but prevents alternate users in the php-fpm group from creating log files.  There is no clean solution here, but having logrotate work is more important than the alternate user use case.  We are working through the implications of removing group write access to `/var/log/php-fpm/`.

**Comment by carlwgeorge** [comment]
Some reference links (mostly notes to my future self):
- https://github.com/logrotate/logrotate/blob/r3-8-0/CHANGES#L6-L8
- https://bugzilla.redhat.com/show_bug.cgi?id=773077
- https://ma.ttias.be/logrotate-on-rhelcentos-7-complains-about-insecure-permissions-on-parent-directory-world-writable/

**Comment by will-parsons** [comment]
For PHP-FPM execution, we used to confgiure the pool with:

```
user = someuser
group = apache
```

On EL6 + php55u at least, this would work, even without having to add `someuser` to the group `apache`.
Will this work on EL7 with `group = php-fpm`, or is this just new Logrotate behavior?

**Comment by carlwgeorge** [comment]
PHP-FPM can run just fine even if a pool can't write it's error log.  But if there is an error, and the pool user can't create files in `/var/log/php-fpm`, the error just doesn't get logged.

The actual issue with logrotate is specific to version 3.8, which wasn't introduced until EL7.

**Comment by tgagor** [comment]
I will be glad knowing at least how do you plan to resolve this issue, so I could adapt my current system configuration to the state compatible with your fix.
I need `logrotate` to work but I don't want to fix this two times :-)

Maybe I could help somehow?

**Comment by carlwgeorge** [comment]
After evaluating several scenarios, we decided to change the `/var/log/php-fpm` permissions to 750.  This removes the ability to add users to the php-fpm group to grant them write access to that location, but the alternate pool user use case can still be achieved with alternate directories.

**Comment by carlwgeorge** [comment]
This is fixed in release [7.0.9-2.ius](https://github.com/iuscommunity-pkg/php70u/releases/tag/7.0.9-2.ius) (and [5.6.24-2.ius](https://github.com/iuscommunity-pkg/php56u/releases/tag/5.6.24-2.ius)), which will move to our testing repositories during tonight's automation.

**Comment by tgagor** [comment]
Thanks four your effort. :+1:

**Comment by carlwgeorge** [comment]
Those releases ([7.0.9-2.ius](https://github.com/iuscommunity-pkg/php70u/releases/tag/7.0.9-2.ius) and [5.6.24-2.ius](https://github.com/iuscommunity-pkg/php56u/releases/tag/5.6.24-2.ius)) will move to our stable repositories during tonight's automation.  Remember that it may take up to 24 hours to propagate to your local mirror.
